[package]
name = "mcp"
version = "0.3.0"
authors = ["Alvaro Polo <apoloval@gmail.com>"]

[dependencies]
byteorder = "1.3.1"
docopt = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
quickcheck = "0.8"
tempdir = "0.3"
